# Generated by Django 4.2.10 on 2024-03-03 16:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_rating_post_id_alter_rating_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user_id', 'post_id')},
        ),
    ]
