# Generated by Django 4.2.10 on 2024-03-03 17:22

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(validators=[posts.models.validate_rate_range]),
        ),
    ]
